// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 32-bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Tue Jul 03 22:41:44 2018

four_state_moore_state_machine four_state_moore_state_machine_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.in(in_sig) ,	// input  in_sig
	.reset(reset_sig) ,	// input  reset_sig
	.out(out_sig) 	// output [1:0] out_sig
);

defparam four_state_moore_state_machine_inst.S0 = 0;
defparam four_state_moore_state_machine_inst.S1 = 1;
defparam four_state_moore_state_machine_inst.S2 = 2;
defparam four_state_moore_state_machine_inst.S3 = 3;
